countries = [
    {'id': 0,
     'name': 'Afghanistan',
     'short_code': 'AFG',
     'flag': '🇦🇫'},
    {'id': 1,
     'name': 'Australia',
     'short_code': 'AUS',
     'flag': '🇦🇺'},
    {'id': 2,
     'name': 'Bangladesh',
     'short_code': 'BAN',
     'flag': '🇧🇩'},
    {'id': 3,
     'name': 'England',
     'short_code': 'ENG',
     'flag': '🏴󠁧󠁢󠁥󠁮󠁧󠁿'},
    {'id': 4,
     'name': 'India',
     'short_code': 'IND',
     'flag': '🇮🇳'},
    {'id': 5,
     'name': 'Netherlands',
     'short_code': 'NED',
     'flag': '🇳🇱'},
    {'id': 6,
     'name': 'New Zealand',
     'short_code': 'NZL',
     'flag': '🇳🇿'},
    {'id': 7,
     'name': 'Pakistan',
     'short_code': 'PAK',
     'flag': '🇵🇰'},
    {'id': 8,
     'name': 'South Africa',
     'short_code': 'RSA',
     'flag': '🇿🇦'},
    {'id': 9,
     'name': 'Sri Lanka',
     'short_code': 'SRI',
     'flag': '🇱🇰'}
]